apiVersion: v1
kind: Service
metadata:
  name: mktsvc-emulator-svc-lb
  namespace: mktsvc
spec:
  selector:
    app: mktsvc-emulator
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 8194
      targetPort: 8194