apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-lb
  namespace: mktsvc
spec:
  selector:
    app: nginx-custom
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80